frontend/routes/web.php
<?php

use App\Http\Controllers\AuthController;
use App\Http\Controllers\CapexReportController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\DataOpcShipmentController;
use App\Http\Controllers\KPIManagementController;
use App\Http\Controllers\MaintenanceCostController;
use App\Http\Controllers\ProjectController;
use App\Http\Controllers\MasterData\MPlantController;
use App\Http\Controllers\Synchronization\OpcController;
use App\Http\Controllers\MasterData\MCostcenterController;
use App\Http\Controllers\MasterData\MCostelementController;
use App\Http\Controllers\MasterData\MAreaController;
use App\Http\Controllers\MasterData\MKondisiController;
use App\Http\Controllers\MasterData\MWorkgroupController;
use App\Http\Controllers\MasterData\MPlantAreaController;
use App\Http\Controllers\MasterData\MEqInspectionController;
use App\Http\Controllers\MasterData\MProjectCapexController;
use App\Http\Controllers\MDataTPMController;
use App\Http\Controllers\Overhaul\OverhaulFinalReportController;
use App\Http\Controllers\Overhaul\OverhaulPreparationController;
use App\Http\Controllers\Overhaul\OverhaulProgressController;
use App\Http\Controllers\PlantReabilityController;
use App\Http\Controllers\OverhoulReportController;
use App\Http\Controllers\PlantInspectionController;
use App\Http\Controllers\PlantOverviewController;
use App\Http\Controllers\PlantPerformanceController;
use App\Http\Controllers\TPMReportController;
use App\Http\Controllers\PowerBIController;
use App\Http\Controllers\ProductionAssetManagementController;
use App\Http\Controllers\TPMReportLaporanGugusController;
use App\Http\Controllers\ProductionReportController;
use App\Http\Controllers\ProductionReportLaporanHarianController;
use App\Http\Controllers\ProductionReportValidasiHarprosController;
use App\Http\Controllers\TPMReportLaporanKPIMemberTPMController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\SparepartPlanningController;
use App\Http\Controllers\Synchronization\ShipmentController;
use App\Http\Controllers\she_safety\DashboardSafetyController;
use App\Http\Controllers\she_safety\ManPowerController;
use App\Http\Controllers\she_safety\ManHoursController;
use App\Http\Controllers\she_safety\AccidentReportController;
use App\Http\Controllers\she_safety\FireAccidentReportController;
use App\Http\Controllers\she_safety\UnsafeActionController;
use App\Http\Controllers\she_safety\UnsafeConditionController;
use App\Http\Controllers\she_safety\AparController;
use App\Http\Controllers\she_safety\FireAlarmController;
use App\Http\Controllers\she_safety\HydrantController;
use App\Http\Controllers\she_safety\SafetyTrainingController;

use App\Http\Controllers\she_safety\MasterJenisLimbahController;
use App\Http\Controllers\she_safety\DokumenLingkunganController;
use App\Http\Controllers\she_safety\MasterInspeskiLingkunganController;
use App\Http\Controllers\she_safety\NeracaLimbahB3Controller;

use App\Http\Controllers\she_proper\KebijakanLingkunganController;
use App\Http\Controllers\she_proper\StrukturOrganController;
use App\Http\Controllers\she_proper\ProgramLingkunganController;
use App\Http\Controllers\she_proper\PerizinanLingkunganController;
use App\Http\Controllers\she_proper\KpiProperController;
use App\Http\Controllers\she_proper\MatrikLingController;
use App\Http\Controllers\she_proper\SertifAnalisController;
use App\Http\Controllers\she_proper\SertifLingController;
use App\Http\Controllers\she_proper\KomPersonilController;
use App\Http\Controllers\she_proper\HasilPengukuranController;



use App\Http\Controllers\Vendor\UploadScheduleController;
use App\Http\Controllers\Vendor\RealisasiFingerprintController;
use App\Http\Controllers\Vendor\PlanningRealisasiFingerprintController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [DashboardController::class, 'index'])->middleware(['feauth']);

Route::get('/dashboard', [DashboardController::class, 'index'])
    ->middleware(['feauth'])
    ->name('dashboard');
// ============================ Dashboard Power BI ==============================
Route::group(['as' => 'powerbi.', 'prefix' => 'powerbi', 'middleware' => 'feauth'], function () {
    Route::get('/', ['as' => 'index', 'uses' => 'PowerBIController@index']);
});

// ============================ Koreksi KPI ==============================
Route::group(['as' => 'koreksi-kpi.', 'prefix' => 'koreksi-kpi', 'middleware' => 'feauth'], function () {
    Route::get('/', ['as' => 'index', 'uses' => 'KoreksiKPIController@index']);
    Route::get('/temp', ['as' => 'temp', 'uses' => 'KoreksiKPIController@temp']);
    Route::get('/create', ['as' => 'create', 'uses' => 'KoreksiKPIController@create']);
    Route::post('/store', ['as' => 'store', 'uses' => 'KoreksiKPIController@store']);
    Route::get('/datatable', ['as' => 'datatable', 'uses' => 'KoreksiKPIController@datatable']);
    Route::post('/download', ['as' => 'download', 'uses' => 'KoreksiKPIController@download']);
});

// ============================ Quality Management ==============================
Route::group(['as' => 'quality-management.', 'prefix' => 'quality-management', 'middleware' => 'feauth'], function () {
    Route::get('/', ['as' => 'index', 'uses' => 'QualityManagementController@index']);
    Route::get('/temp-rm', ['as' => 'tempRM', 'uses' => 'QualityManagementController@tempRM']);
    Route::get('/temp-kf', ['as' => 'tempKF', 'uses' => 'QualityManagementController@tempKF']);
    Route::get('/temp-ck', ['as' => 'tempCK', 'uses' => 'QualityManagementController@tempCK']);
    Route::get('/temp-se', ['as' => 'tempSE', 'uses' => 'QualityManagementController@tempSE']);
    Route::get('/temp-cm', ['as' => 'tempCM', 'uses' => 'QualityManagementController@tempCM']);
    Route::get('/temp-hm', ['as' => 'tempHM', 'uses' => 'QualityManagementController@tempHM']);
    Route::get('/edit-rm/{uuid}', ['as' => 'editRM','uses' => 'QualityManagementController@editRM']);
    Route::get('/edit-kf/{uuid}', ['as' => 'editKF','uses' => 'QualityManagementController@editKF']);
    Route::get('/edit-ck/{uuid}', ['as' => 'editCK','uses' => 'QualityManagementController@editCK']);
    Route::get('/edit-se/{uuid}', ['as' => 'editSE','uses' => 'QualityManagementController@editSE']);
    Route::get('/edit-cm/{uuid}', ['as' => 'editCM','uses' => 'QualityManagementController@editCM']);
    Route::get('/edit-hm/{uuid}', ['as' => 'editHM','uses' => 'QualityManagementController@editHM']);

    // ==== Modal ====
    Route::get('/modal-import-rm', ['as' => 'importRM', 'uses' => 'QualityManagementController@importRM']);
    Route::get('/modal-import-kf', ['as' => 'importKF', 'uses' => 'QualityManagementController@importKF']);
    Route::get('/modal-import-ck', ['as' => 'importCK', 'uses' => 'QualityManagementController@importCK']);
    Route::get('/modal-import-se', ['as' => 'importSE', 'uses' => 'QualityManagementController@importSE']);
    Route::get('/modal-import-cm', ['as' => 'importCM', 'uses' => 'QualityManagementController@importCM']);
    Route::get('/modal-import-hm', ['as' => 'importHM', 'uses' => 'QualityManagementController@importHM']);

    // ==== API ====
    Route::post('/store-rm', ['as' => 'storeRM', 'uses' => 'QualityManagementController@storeRM']);
    Route::post('/store-kf', ['as' => 'storeKF', 'uses' => 'QualityManagementController@storeKF']);
    Route::post('/store-ck', ['as' => 'storeCK', 'uses' => 'QualityManagementController@storeCK']);
    Route::post('/store-se', ['as' => 'storeSE', 'uses' => 'QualityManagementController@storeSE']);
    Route::post('/store-cm', ['as' => 'storeCM', 'uses' => 'QualityManagementController@storeCM']);
    Route::post('/store-hm', ['as' => 'storeHM', 'uses' => 'QualityManagementController@storeHM']);
    Route::get('/datatable-rm', ['as' => 'datatableRM', 'uses' => 'QualityManagementController@datatableRM']);
    Route::get('/datatable-kf', ['as' => 'datatableKF', 'uses' => 'QualityManagementController@datatableKF']);
    Route::get('/datatable-ck', ['as' => 'datatableCK', 'uses' => 'QualityManagementController@datatableCK']);
    Route::get('/datatable-se', ['as' => 'datatableSE', 'uses' => 'QualityManagementController@datatableSE']);
    Route::get('/datatable-cm', ['as' => 'datatableCM', 'uses' => 'QualityManagementController@datatableCM']);
    Route::get('/datatable-hm', ['as' => 'datatableHM', 'uses' => 'QualityManagementController@datatableHM']);
    Route::put('/edit-rm/{uuid}', ['as' => 'updateRM', 'uses' => 'QualityManagementController@updateRM']);
    Route::put('/edit-kf/{uuid}', ['as' => 'updateKF', 'uses' => 'QualityManagementController@updateKF']);
    Route::put('/edit-ck/{uuid}', ['as' => 'updateCK', 'uses' => 'QualityManagementController@updateCK']);
    Route::put('/edit-se/{uuid}', ['as' => 'updateSE', 'uses' => 'QualityManagementController@updateSE']);
    Route::put('/edit-cm/{uuid}', ['as' => 'updateCM', 'uses' => 'QualityManagementController@updateCM']);
    Route::put('/edit-hm/{uuid}', ['as' => 'updateHM', 'uses' => 'QualityManagementController@updateHM']);
    Route::delete('/delete-rm/{uuid}', ['as' => 'deleteRM', 'uses' => 'QualityManagementController@deleteRM']);
    Route::delete('/delete-kf/{uuid}', ['as' => 'deleteKF', 'uses' => 'QualityManagementController@deleteKF']);
    Route::delete('/delete-ck/{uuid}', ['as' => 'deleteCK', 'uses' => 'QualityManagementController@deleteCK']);
    Route::delete('/delete-se/{uuid}', ['as' => 'deleteSE', 'uses' => 'QualityManagementController@deleteSE']);
    Route::delete('/delete-cm/{uuid}', ['as' => 'deleteCM', 'uses' => 'QualityManagementController@deleteCM']);

frontend/app/Http/Controllers/Production/CementReportsController.php
<?php

namespace App\Http\Controllers\Production;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class CementReportsController extends Controller
{
    //
    protected $title;
    protected $route;
    protected $endpoint;

    public function __construct()
    {
        $this->title = 'Cement Production';
        $this->route = 'production.cement';
        $this->endpoint = 'production/cement';
    }

    public function index()
    {
        $page_title = $this->title;
        $page_description = '';
        $data = [
            'pagetitle' => $page_title,
            'subtitle' => 'report ' . strtolower($page_title),
            'route' => $this->route,
            'breadcrumb' => ['Production' => null, $page_title => route($this->route.'.index') ],
        ];
        addVendors(['datatables']);
        return view('pages.'.$this->route . '.index', compact('page_title', 'page_description'), $data);        
    }

    public function table(Request $request){
        return HttpTable($request, $this->endpoint);
    }
}

frontend/app/Http/Controllers/Production/ClinkerReportsController.php
<?php

namespace App\Http\Controllers\Production;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ClinkerReportsController extends Controller
{
    //
    protected $title;
    protected $route;
    protected $endpoint;

    public function __construct()
    {
        $this->title = 'Clinker Production';
        $this->route = 'production.clinker';
        $this->endpoint = 'production/clinker';
    }

    public function index()
    {
        $page_title = $this->title;
        $page_description = '';
        $data = [
            'pagetitle' => $page_title,
            'subtitle' => 'report ' . strtolower($page_title),
            'route' => $this->route,
            'breadcrumb' => ['Production' => null, $page_title => route($this->route.'.index') ],
        ];
        addVendors(['datatables']);
        return view('pages.'.$this->route . '.index', compact('page_title', 'page_description'), $data);        
    }

    public function table(Request $request){
        return HttpTable($request, $this->endpoint);
    }
}

frontend/app/Http/Controllers/Production/CoalMillReportsController.php
<?php

namespace App\Http\Controllers\Production;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class CoalMillReportsController extends Controller
{
    //
    protected $title;
    protected $route;
    protected $endpoint;

    public function __construct()
    {
        $this->title = 'Coal Mill Production';
        $this->route = 'production.coalmill';
        $this->endpoint = 'production/coalmill';
    }

    public function index()
    {
        $page_title = $this->title;
        $page_description = '';
        $data = [
            'pagetitle' => $page_title,
            'subtitle' => 'report ' . strtolower($page_title),
            'route' => $this->route,
            'breadcrumb' => ['Production' => null, $page_title => route($this->route.'.index') ],
        ];
        addVendors(['datatables']);
        return view('pages.'.$this->route . '.index', compact('page_title', 'page_description'), $data);        
    }

    public function table(Request $request){
        return HttpTable($request, $this->endpoint);
    }
}

frontend/app/Http/Controllers/Production/CrusherReportsController.php
<?php

namespace App\Http\Controllers\Production;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class CrusherReportsController extends Controller
{
    //
    protected $title;
    protected $route;
    protected $endpoint;

    public function __construct()
    {
        $this->title = 'Crusher Production';
        $this->route = 'production.crusher';
        $this->endpoint = 'production/crusher';
    }

    public function index()
    {
        $page_title = $this->title;
        $page_description = '';
        $data = [
            'pagetitle' => $page_title,
            'subtitle' => 'report ' . strtolower($page_title),
            'route' => $this->route,
            'breadcrumb' => ['Production' => null, $page_title => route($this->route.'.index') ],
        ];
        addVendors(['datatables']);
        return view('pages.'.$this->route . '.index', compact('page_title', 'page_description'), $data);        
    }

    public function table(Request $request){
        return HttpTable($request, $this->endpoint);
    }
}

frontend/app/Http/Controllers/Production/PackerReportsController.php
<?php

namespace App\Http\Controllers\Production;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class PackerReportsController extends Controller
{
    //
    protected $title;
    protected $route;
    protected $endpoint;

    public function __construct()
    {
        $this->title = 'Packer Production';
        $this->route = 'production.packer';
        $this->endpoint = 'production/packer';
    }

    public function index()
    {
        $page_title = $this->title;
        $page_description = '';
        $data = [
            'pagetitle' => $page_title,
            'subtitle' => 'report ' . strtolower($page_title),
            'route' => $this->route,
            'breadcrumb' => ['Production' => null, $page_title => route($this->route.'.index') ],
        ];
        addVendors(['datatables','amcharts4']);
        return view('pages.'.$this->route . '.index', compact('page_title', 'page_description'), $data);        
    }

    public function table(Request $request){
        return HttpTable($request, $this->endpoint);
    }

    public function status(Request $request){
        return HttpTable($request, $this->endpoint.'status');
    }

    public function silo(Request $request){
        return HttpGet($request,'',$this->endpoint.'silo');
    }
}

frontend/app/Http/Controllers/Production/ProdutctionIndexReportsController.php
<?php

namespace App\Http\Controllers\Production;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ProdutctionIndexReportsController extends Controller
{
    //
    protected $title;
    protected $route;
    protected $endpoint;

    public function __construct()
    {
        $this->title = 'Production Index Report';
        $this->route = 'production.prodindex';
        $this->endpoint = 'production/prodindex';
    }

    public function index()
    {
        $page_title = $this->title;
        $page_description = '';
        $data = [
            'pagetitle' => $page_title,
            'subtitle' => 'report ' . strtolower($page_title),
            'route' => $this->route,
            'breadcrumb' => ['Production' => null, $page_title => route($this->route.'.index') ],
        ];
        addVendors(['datatables']);
        return view('pages.'.$this->route . '.index', compact('page_title', 'page_description'), $data);        
    }

    public function table(Request $request){
        return HttpTable($request, $this->endpoint);
    }
}

frontend/app/View/Components/DefaultLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class DefaultLayout extends Component
{
    /**
     * Create a new component instance.
     *
     * @return void
     */
    public function __construct()
    {
        //
    }

    /**
     * Get the view / contents that represent the component.
     *
     * @return \Illuminate\Contracts\View\View|\Closure|string
     */
    public function render()
    {
        return view(config('settings.KT_THEME_LAYOUT_DIR').'._default');
    }
}

frontend/resources/views/pages/production/cement/index.blade.php
<x-default-layout>
    <!--begin::Row-->
    <div class="row g-5 g-xl-10 mb-5 mb-xl-10">
        <div class="card card-executive-summary">
            <div class="card-header">
                <div class="card-title">
                    <span>{{$pagetitle}}</span>
                </div>

                <div class="card-toolbar my-1">
                    <div class="me-6 my-1">
                        Tanggal Report
                    </div>
                    <div class="me-6 my-1">
                        <input type="text" id="filter_tanggal" class="form-control form-control-solid form-select-sm w-150px ps-9" value="{{date('d-m-Y', strtotime('yesterday'))}}">
                    </div>
                </div>
            </div>

            <div class="card-body">
                <div class="dataTables_wrapper dt-bootstrap4 no-footer">
                    <div class="table-responsive">
                        <table id="datatable-crusher" class="table table-row-bordered table-row-dashed gy-4 align-middle fw-bold dataTable no-footer" style="width:100%">
                            <thead class="fs-7 text-gray-400 text-uppercase">
                                <tr>
                                    <th></th>
                                    <th colspan=3>Tuban 1</th>
                                    <th colspan=2>Tuban 2</th>
                                    <th colspan=2>Tuban 3</th>
                                    <th colspan=2>Tuban 4</th>
                                </tr>
                                <tr>
                                    <th></th>
                                    <th>FM 1</th>
                                    <th>FM 2</th>
                                    <th>FM 9</th>
                                    <th>FM 3</th>
                                    <th>FM 4</th>
                                    <th>FM 5</th>
                                    <th>FM 6</th>
                                    <th>FM 7</th>
                                    <th>FM 8</th>
                                </tr>
                            </thead>
                            <tbody>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</x-default-layout>

<script>
    var reportTable;
    $(document).ready(function () {
        reportTable = $('#datatable-crusher').DataTable({
            processing: true,
            serverSide: true,
            searching: false,
            paging:false,
            order: [],
            ajax: {
                url: "{{route($route . '.table')}}",
                data: function (d) {
                    d.tgl_report = $('#filter_tanggal').val();
                    // d.custom = $('#myInput').val();
                    // etc
                },
            },
            columns: [
                {
                    data: 'keterangan',
                    name: 'keterangan'
                },
                {
                    data: 'FM 1 Tuban 1',
                    name: 'FM 1 Tuban 1',
                    render: function(data, type, row){
                        return localeString(data);
                    }
                },
                {
                    data: 'FM 2 Tuban 1',
                    name: 'FM 2 Tuban 1',
                    render: function(data, type, row){
                        return localeString(data);
                    }
                },
                {
                    data: 'FM 9 Tuban 1',
                    name: 'FM 9 Tuban 1',
                    render: function(data, type, row){
                        return localeString(data);
                    }
                },
                {
                    data: 'FM 1 Tuban 2',
                    name: 'FM 1 Tuban 2',
                    render: function(data, type, row){
                        return localeString(data);
                    }
                },
                {
                    data: 'FM 2 Tuban 2',
                    name: 'FM 2 Tuban 2',
                    render: function(data, type, row){
                        return localeString(data);
                    }
                },
                {
                    data: 'FM 1 Tuban 3',
                    name: 'FM 1 Tuban 3',
                    render: function(data, type, row){
                        return localeString(data);
                    }
                },
                {
                    data: 'FM 2 Tuban 3',
                    name: 'FM 2 Tuban 3',
                    render: function(data, type, row){
                        return localeString(data);
                    }
                },
                {
                    data: 'FM 1 Tuban 4',
                    name: 'FM 1 Tuban 4',
                    render: function(data, type, row){
                        return localeString(data);
                    }
                },
                {
                    data: 'FM 2 Tuban 4',
                    name: 'FM 2 Tuban 4',
                    render: function(data, type, row){
                        return localeString(data);
                    }
                },
            ]
        });
        $('#filter_tanggal').flatpickr({
            dateFormat: "d-m-Y",
            onChange: function(dt){
                reportTable.ajax.reload();
            },
        });
    });

    function localeString(num){
        if(!isNaN(num)){
            return num.toLocaleString("id-Id",{maximumFractionDigits : 2});
        }
        else{
            if(num == 'OFF'){
                return '<span class="fa fa-power-off fa-lg" style="color:red"></span>';
            }
            else{
                return '<span class="fa fa-power-off fa-lg" style="color:green"></span>';
            }
        }
    }

</script>